### ISSUE TITLE
Token Refresh / Revoke not Included in Conformance Requirements

### ISSUE THREAD

**Issue by mlyon-ims** [1EdTech/openbadges-specification#459]
This is described in the spec document, but not mentioned in the conformance requirements.

**Comment by mlyon-ims** [comment]
Proposal: Verify in the conformance requirements that this is NOT required.

**Comment by ottonomy** [comment]
Including a refresh token in the initial token Grant is optional. But if the refresh token is included, it seems like we could test conformance of the refresh token endpoint if we want.

**Comment by martyr280** [comment]
+1 for @mlyon-ims proposal

**Comment by justinpitcher** [comment]
My reaction is that testing refresh token behaviour isn't strictly necessary, as it becomes a test of another spec.
