### ISSUE TITLE
credentialSubject Type Question

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#471]
According to the schema, credentialSubject.type should be an array. What other type will a credentialSubject be while it is an AchievementSubject". Are all types required to be arrays in this schema, and if so, is that correct?

**Comment by mgylling** [comment]
Currently the CredentialSubject type prop follows the design pattern of VC.type, i.e. multiple type values. Because of the absence of type coercion in the draft, it is always an array (cf. #473). For working group discussion. 

@kayaelle What approach would you like to see here?

**Comment by martyr280** [comment]
@kayaelle do you have a proposal here?

**Comment by xaviaracil** [comment]
Solved in working group meeting on 10/22: Add compaction support for arrays .
