### ISSUE TITLE
Required Items for Proof

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#472]
Items required for proof including "created", "proofPurpose", "proofValue", and "verificationMethod" aren't required by the VC spec which states:

"Because the method used for a mathematical proof varies by representation language and the technology used, the set of name-value pairs that is expected as the value of the proof [property](https://www.w3.org/TR/vc-data-model/#dfn-property) will vary accordingly. For example, if digital signatures are used for the proof mechanism, the proof [property](https://www.w3.org/TR/vc-data-model/#dfn-property) is expected to have name-value pairs that include a signature, a reference to the signing entity, and a representation of the signing date."

When a proof is embedded, the type property is required. Otherwise, the required properties depend on the method specified as the value of the type.

[https://www.w3.org/TR/vc-data-model/#proofs-signatures](https://www.w3.org/TR/vc-data-model/#proofs-signatures)

It's suggested that OBv3 not add any additional requirements for proofs and rely on the VC model to determine this.

**Comment by mgylling** [comment]
Comment from Andy: probably a mistake in editing to make these properties generally required. We should follow VC here. In terms of the Edwards Curve however, note that a bunch of these properties are actually required. We need to distinguish these two cases in the spec.

**Comment by martyr280** [comment]
+1 to @kayaelle proposal

**Comment by longpd** [comment]
+1 here as well.

**Comment by tcouper** [comment]
+1

**Comment by xaviaracil** [comment]
Solved in working group meeting on 10/22: Change cardinality of those attributes for matching VC spec
