### ISSUE TITLE
Proof Requirement

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#476]
The proof property description of AchievementCredential states "If present, one or more embedded cryptographic proofs that can be used to detect tampering and verify the authorship of the credential."

The Verifiable Credential model states "At least one proof mechanism, and the details necessary to evaluate that proof, MUST be expressed for a [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) or [presentation](https://www.w3.org/TR/vc-data-model/#dfn-presentations) to be a [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) or [verifiable presentation](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations); that is, to be [verifiable](https://www.w3.org/TR/vc-data-model/#dfn-verify)."

An Open Badge should require that at least one proof is expressed.

**Comment by martyr280** [comment]
@mgylling can we discuss this one at the workgroup tomorrow?

**Comment by justinpitcher** [comment]
The VC model does not require the proof property. It is only required when the mechanism is an embedded proof. The description for AchievementCredential is correct/consistent with VC.

But I agree with @mgylling about revisiting the descriptive text to make this clearer.

**Comment by xaviaracil** [comment]
Solved in working group meeting on 10/22: Add clarification
