### ISSUE TITLE
Criteria Requirements

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#477]
Criteria is a required property that references the Criteria class but there are no required elements in the class. Should id or narrative be required.

**Comment by mgylling** [comment]
For context and in advance of the working group discussion: In OB20, the [Criteria class](http://imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Criteria) had no required properties. 

However, making one or both of id or narrative required may be an improvement.

**Comment by ottonomy** [comment]
The design is hard to express in terms of one property being required, it's that at least one of them is required. Is that something that we should try to enforce at the JSON-schema level, out would that be too complicated?

I would be ok with making the narrative required, even if it just meant instructing people to use an empty string if they just wanted to provide an external URL.

**Comment by martyr280** [comment]
@ottonomy I vote for simplicity, we should discuss at 10/20 workgroup

**Comment by justinpitcher** [comment]
Interesting point, Phil.

**Comment by ottonomy** [comment]
@longpd do you have an example of how an embedded ID property inside another JSON document enables a hashlink, specifically in the way you're suggesting? I can see how it could enable identification of a sub-section of a JSON document using a [URI Fragment](https://en.wikipedia.org/wiki/URI_fragment) (The part of the URI or IRI referring to a subordinate resource within a primary resource, separated from the URL path with a hash sign `#`), but I don't see how it could enable something like a hashlink, which I understand to be content-addressable identifiers. 

See an [example](https://w3c-ccg.github.io/did-method-web/#example-example-did-web-did-document-using-secp256) in the did:web method spec, where a subordinate resource of a key is identified as `did:web:example.com#controller` within a DID Document identified as `did:web:example.com`. 

Whereas hashlinks (for example the [2021 draft](https://datatracker.ietf.org/doc/html/draft-sporny-hashlink-07) of the concept of cryptographic hashlinks from @msporny) are about ensuring data fetchable from a certain URL has not been modified from a previously known state. 

Are you conflating these two uses of "hash", or are you suggesting that there are communities that are combining these methodologies through JSON-LD canonicalization and hashing of subordinate sections of JSON-LD documents that are identified using IRIs with fragments?



---

Similar to other discussions of when IDs are required, I am generally not opposed to requiring IDs that could be UUIDs when there are significantly valuable use cases that depend on ids existing. As long as we put appropriate considerations in place for not being able to ensure that such "uuids" actually *are* locally or "universally" unique.

**Comment by xaviaracil** [comment]
Solved in working group meeting on 10/22: Add soft requirement
