### ISSUE TITLE
Add Terms of Use

### ISSUE THREAD

**Issue by David-Chadwick** [1EdTech/openbadges-specification#479]
The terms of use (ToU) VC property is an important property that should be included in OpenBadges. Quote from the W3C VCDM "to communicate the terms under which a VC was issued".

We are using the ToU in order to scale the trustworthiness of the badge issuing infrastructure. In a global open badge world there will be thousands (perhaps millions) of badge issuers. It is unrealistic to expect any verifier to know who is a genuine badge issuer and who is a fraudster. Verifiers will need to rely on a trust infrastructure to tell them.

The eSSIF TRAIN project built such a trust infrastructure, using the DNS, web pages and the ETSI Trust List standard. In this model a trust scheme operator publishes a list of all the issuers who are genuine (i.e. trustworthy) in a digitally signed ETSI Trust List, pointed to from the DNS name of the trust scheme. TRAIN also offers an open source API for verifiers to call, making incorporation of the trust scheme a trivial operation (only a few lines of code are needed).

Issuers insert into the ToU property the trust scheme(s) they are members of, meaning that this VC was issued according to the terms of this trust scheme(s). 

Verifiers extract the trust scheme from the ToU, and then call the TRAIN API asking it if this issuer is a member of this trust scheme, and will get a positive or negative answer, indicating whether this is a trusworthy badge issuer or not.

This is not the only use for the ToU property. Other examples include: to indicate that the badge is not transferrable, to limit the liability of the issuer etc.

**Comment by ottonomy** [comment]
@David-Chadwick could you provide an example of the JSON data that you propose would be added to a credential to accomplish this and implement the ETSI Trust List standard? Is there a best link to that standard that shows how data related to trust lists like this are provided in credentials?

Context: some basic info about the termsOfUse property is [here in the VC Data Model](https://www.w3.org/TR/vc-data-model/#terms-of-use). The VC Data Model doesn't specify all of the sub-properties that would likely be used under this property, just `id` and `type`.

There should be no issue adding this data to credentials that would cause the credential to become an invalid Open Badges 3.0 AchievementCredential.

I suggest this not be considered as a new 3.0 use case but that the workgroup acknowledge that the concept of trust registries is important to a successful mature ecosystem of credentials. I think there's a lot of room here for market players to show successful implementation patterns, and that we shouldn't rush to describe one specific method before the many different groups in the space that are working on this problem settle on solutions. VC.termsOfUse might be used in some of these approaches, and the current draft of the spec shouldn't be a barrier to anyone implementing an approach here. I'm sure a number of OB implementers would be happy to consider collaborating around use cases here.

**Comment by David-Chadwick** [comment]
Hi Nate
    
    On 02/11/2022 23:18, Nate Otto wrote:
    
    
      
      @David-Chadwick could you provide
        an example of the JSON data that you propose would be added to a
        credential to accomplish this and implement the ETSI Trust List
        standard? Is there a best link to that standard that shows how
        data related to trust lists like this are provided in
        credentials?
    
    The process is very simple for VC Issuers. They add the following
      property to the VCs they issue
    "termsOfUse": [{
          "type": "https://train.trust-scheme.de/info",
          "trustScheme": [ “dns.name.of.the.trust.scheme”]
      }] 
    The process is equally simple for VC Verifiers as there is open
      source code that implements the verification of this terms of use,
      produced by Fraunhofer, under the eSSIF-lab subproject TRAIN. The
      system is fully described in this paper.
    Isaac Henderson Johnson Jeyakumar, David W Chadwick and Michael
      Kubach. “A novel approach to establish trust in verifiable
      credential issuers in Self-sovereign identity ecosystems using
      TRAIN” Open Identity Summit 2022, July 7th and 8th, 2022, by DTU
      Compute in Lyngby, Denmark. Available at
      https://dl.gi.de/handle/20.500.12116/38702
    The verifier simply calls the TRAIN API, passing it the URI of
      the issuer and the “dns.name.of.the.trust.scheme”. The TRAIN API
      tells the verifier if the issuer is a trusted member of this trust
      scheme or not.
    The most difficult work is done by the administrator of the trust
      scheme as they have to produce the rules for their trust scheme,
      verify that issuers abide by these rules, then add the issuer's
      details to the ETSI trust list, published this (digitally signed)
      list on a web page, and then update their DNS entry to point to
      this web page.
    
    The ETSI standard is publicly available here
    https://www.etsi.org/deliver/etsi_ts/119600_119699/119612/02.02.01_60/ts_119612v020201p.pdf
    As part of the NGI Atlantic project "Next generation SSI
      Standards" we have just specified how TRAIN can be extended to
      support trusted verifiers and trusted wallet software providers as
      well. Fraunhofer is currently enhancing their API to support these
      as well.
    
    
      Context: some basic info about the termsOfUse
        property is here in the VC Data
          Model. The VC Data Model doesn't specify all of the
        sub-properties that would likely be used under this property,
        just id and type.
      There should be no issue adding this data to
        credentials that would cause the credential to become an invalid
        Open Badges 3.0 AchievementCredential.
      I suggest this not be considered as a new 3.0 use
        case but that the workgroup acknowledge that the concept of
        trust registries is important to a successful mature ecosystem
        of credentials. I think there's a lot of room here for market
        players to show successful implementation patterns, and that we
        shouldn't rush to describe one specific method before the many
        different groups in the space that are working on this problem
        settle on solutions. VC.termsOfUse might be used in some of
        these approaches, and the current draft of the spec shouldn't be
        a barrier to anyone implementing an approach here. I'm sure a
        number of OB implementers would be happy to consider
        collaborating around use cases here.
    
    The other player in this space is the OIDF GAIN project. It is
      specifying methods for different trust methods to interwork
      together by using OIDC Federation draft standard. I have been
      designing how TRAIN can fit into GAIN.
    
    Kind regards
    David
    
    
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/IMSGlobal/openbadges-specification/issues/479#issuecomment-1301482442",
"url": "https://github.com/IMSGlobal/openbadges-specification/issues/479#issuecomment-1301482442",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
