### ISSUE TITLE
add requirements section

### ISSUE THREAD

**Issue by Sakurann** [1EdTech/openbadges-specification#490]
For example, it took me a while to locate requirements for the identifiers (quoted below) - it would be much cleaner if there is a separate section summarizing all the requirements in the beginning of the document.

> This specification allows the use of an HTTP URL (e.g. https://1edtech.org/keys/1) or a DID URL (e.g. did:key:123), but only requires HTTP URL support.

**Comment by xaviaracil** [comment]
Don't know if the spec file is the right place for this section, or it may fit better in the Implementation Guide.

**Comment by xaviaracil** [comment]
The implementation guide has already a section about requirements
