### ISSUE TITLE
add cryptosuite requirements

### ISSUE THREAD

**Issue by Sakurann** [1EdTech/openbadges-specification#491]
From my experience, supported cryptosuites are crucial for interoperability. 
It would help interoperability to have a set of recommended crypto suites, maybe one mandatory to implement.
It is also helpful to define which suite is required for signing/verification - it is much easier for implementers if they can sign using only one alg, but can verify using several algs that are supported by the implementers in the ecosystem.

**Comment by jischr** [comment]
I do believe crypto suite is already defined here:
https://imsglobal.org/spec/ob/v3p0/draft#joseheader

RS256 to ensure interop, others allowed.

**Comment by xaviaracil** [comment]
The implementation guide has already a section about signing and cryptosuites
