### ISSUE TITLE
JSON Schema is overly strict, conflicts with extensibility model of W3C VCs

### ISSUE THREAD

**Issue by tplooker** [1EdTech/openbadges-specification#500]
As un-covered during the recent JFF plugfest, the current JSON schema representation for OBV3 is overly strict with respect to allowing additional properties in a VC that aren't directly defined by OBV3, one such example is [credentialStatus](https://w3c.github.io/vc-data-model/#status) a property which is valid in the context of W3C VC's but is not permitted by OBV3's schema definition. I would suggest relaxing this constraint in the schema definition to resolve this issue.

**Comment by tplooker** [comment]
Another such example is [local contexts](https://www.w3.org/TR/json-ld/#dfn-local-context) for JSON-LD are not supported because the `@context` member defined in the schema requires all members of the array to be strings instead of also allowing objects.

**Comment by dmitrizagidulin** [comment]
+1 to what Tobias is saying, above.

**Comment by justinpitcher** [comment]
@tplooker where are you seeing credentialStatus not being permitted?

It's part of the AchievementCredential's JSON schema and the spec references a new 1EdTech status extension that may be used with that property:

https://imsglobal.org/spec/vcrl/v1p0/

**Comment by xaviaracil** [comment]
What @tplooker is trying to say, if I got it right, is that our schema don't permit additional properties in `credentialStatus`, when they're permitted in W3C VCs.

His suggestion, so, is to make `credentialStatus` extensible, so the schema would allow these additional properties.

**Comment by kayaelle** [comment]
I believe that's correct @xaviaracil. Open Badges has historically allowed for additional properties that are mentioned in the spec. This is critical because additional contexts may be used in a credential. For example, CTDL properties could be added to a badge.

**Comment by amiller-ims** [comment]
> What @tplooker is trying to say, if I got it right, is that our schema don't permit additional properties in `credentialStatus`, when they're permitted in W3C VCs.
> 
> His suggestion, so, is to make `credentialStatus` extensible, so the schema would allow these additional properties.

Agree. I overlooked [these sentences](https://www.w3.org/TR/vc-data-model/#status) when I first modeled `credentialStatus`:

> The precise contents of the credential status information is determined by the specific credentialStatus type definition, and varies depending on factors such as whether it is simple to implement or if it is privacy-enhancing.

They imply that a CredentialStatus object may have additional properties beyond the required `id` and `type`.

Additional properties are currently allowed on many, but not all objects in the OB model. Unexpected additional properties can hinder interoperability for some implementors. That is why the schema does not blindly allow additional properties for every object. Now (while the standard is still a draft) is a great time to make the case why specific objects should allow additional properties.

**Comment by amiller-ims** [comment]
> Another such example is [local contexts](https://www.w3.org/TR/json-ld/#dfn-local-context) for JSON-LD are not supported because the `@context` member defined in the schema requires all members of the array to be strings instead of also allowing objects.

That was intentional. [While you are developing/testing an extension](https://www.imsglobal.org/node/205746#extending), you can treat `@context` as a graph. But when it comes time to share your extension, you should create and host a context file with your extension's properties and objects.

**Comment by ottonomy** [comment]
Two issues in this issue, and my rushed ill-considered reaction:

* Open Badges 2.0 was indeed not strict about what the value of the `@context` property was in the original JSON. I personally am not too concerned about us putting some further restrictions on this. Couldn't implementers just compact their documents into a compliant context that meets requirements of the spec when documents will be checked against JSON-schema?
* I agree that credentialStatus should allow additionalProperties.

**Comment by xaviaracil** [comment]
As decided by the working group: credentialStatus should allow additionalProperties.

**Comment by dmitrizagidulin** [comment]
I think similarly, 'credentialSubject' should allow additional properties.

**Comment by amiller-ims** [comment]
+1

Arguably the most likely object to be extended.

**Comment by kayaelle** [comment]
It would also be good if issuer could allow additional properties.

**Comment by amiller-ims** [comment]
`issuer` is of type Profile which does allow additional properties. It's not super obvious, but the phrase "This class can be extended with additional properties" appears at the bottom of the class model.

https://www.imsglobal.org/spec/ob/v3p0/#profile

**Comment by kayaelle** [comment]
Thanks, @andyfmiller. I was able to confirm that additional properties may be added to issuer without error.

**Comment by xaviaracil** [comment]
Reopened for relaxing context restrictions

**Comment by amiller-ims** [comment]
I think allowing [local contexts](https://www.w3.org/TR/json-ld/#dfn-local-context) during certification testing will hinder, not enhance interoperability in the market using the OB3 and CLR2 standards. If you are not seeking certification any valid form of `@context` is allowed.

Note that the VC2.0 workgroup also define `@context` as an [array of strings](https://github.com/w3c/vc-data-model/blob/main/schema/verifiable-credential/verifiable-credential-schema.json#L139-L148).
