### ISSUE TITLE
credentialSchema Requires an Array

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#506]
The schema for AchievementCredential requires that credentialSchema be an array but it should be an object. 

I can't seem to find an example of there being more than one schema in a credential. 

For reference: https://w3c-ccg.github.io/vc-json-schemas/v1/index.html

**Comment by amiller-ims** [comment]
The `credentialSchema` property is an array of CredentialSchema objects per VC-DATA-MODEL [5.4 Data Schemas](https://www.w3.org/TR/vc-data-model/#data-schemas):

> The value of the `credentialSchema` property MUST be one or more data schemas that provide verifiers with enough information to determine if the provided data conforms to the provided schema. Each credentialSchema MUST specify its `type` (for example, JsonSchemaValidator2018), and an `id` property that MUST be a URI identifying the schema file. The precise contents of each data schema is determined by the specific type definition.

**Comment by kayaelle** [comment]
That's true but the schema doesn't need to require credentialSchema to be an array. Please see https://github.com/1EdTech/openbadges-specification/pull/494
