### ISSUE TITLE
Requirement does not align with statement in "Compacted document form"

### ISSUE THREAD

**Issue by amiller-ims** [1EdTech/openbadges-specification#509]
This is a requirement because of the term _MUST_:

https://github.com/1EdTech/openbadges-specification/blob/5fadca6d254fe156ab831dd42a7b1f8ef7c18d3e/ob_v3p0/serialization.md?plain=1#L13

**Comment by xaviaracil** [comment]
Relaxing requirement to *SHOULD*:

https://github.com/1EdTech/openbadges-specification/blob/65c75d1f2ffa08d7dbdb48a7380f589894c0355d/ob_v3p0/serialization.md?plain=1#L13-L14
