### ISSUE TITLE
Statement about compacting

### ISSUE THREAD

**Issue by amiller-ims** [1EdTech/openbadges-specification#510]
The statement below conflicts with the [conformance statement](https://www.imsglobal.org/spec/ob/v3p0#conformance) in section[ A.1 JSON](https://www.imsglobal.org/spec/ob/v3p0#json),

> Sequence values MUST be represented as an JSON Array, NOT as a single value.

https://github.com/1EdTech/openbadges-specification/blob/5fadca6d254fe156ab831dd42a7b1f8ef7c18d3e/ob_v3p0/serialization.md?plain=1#L44

Also the statement could be improved by using _MAY_ instead of "permits". For example, 

> ...Open Badges verifiable credentials MAY use singular values compaction in the...

One more thing: I don't think the JSON-LD context is what permits or restricts array compaction of the serialized JSON. It is the JSON binding of the data model, i.e. the JSON Schema. It is nice to know why the JSON can be serialized this way. Maybe this section should be moved under the "A.1 JSON" with the last paragraph worded like this:

~~> Some properties -- as noted in the Data Model -- with multiplicity `[0..*]` or `[1..*]` MAY be rendered in JSON as singular values when having only one value, or an an array of values when having one or more values.~~

~~This assumes the Data Model is updated to indicate which properties this applies to. If that is not possible, then this section of the spec should explicitly list the properties that can be serialized in this way.~~

After thinking about this more, I realized this special JSON serialization should not appear in the data model. The Data Model is intentionally separate from the binding (e.g. JSON or XML serialization). I think the better idea is to move "Compact document form" under "A.1 JSON" since it applies to JSON serialization. And the properties that MAY be serialized in this way should be explicitly listed.

**Comment by xaviaracil** [comment]
Agree on *MAY* instead of "permits".

Aggee on the fact that is the schema which permits this compaction. My main concern, though, is moving this out of the JSON-LD section. I mean, nothing stops this compaction to be done on plain json documents, but the compaction algorithm is defined in the JSON-LD-API. That said, I would "restrict" the application of this algorithm (and so, the ability of the schema to allow single values in array properties) only to the json-ld representation of the data model.

**Comment by amiller-ims** [comment]
>  @andyfmiller after your edits, do you still feel that there needs to be any change to the spec?

@ottonomy No. _MAY_ was the most important to me. I think the section (which originated in OB21/CLR1 is getting better. Probably one more edit to address the incorrect statement you found will be enough to put this section to bed.
