### ISSUE TITLE
We should be clear about how implementors should consider changes

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/openbadges-specification#514]
We've come to the agreement on the technical calls that we have (at least) this policy around changes:
- adding new terms to the model/context _is not_ a breaking change
- changing term mappings or removing terms _is_ a breaking change

This policy implies that a downstream consumer must be willing to be forgiving on the data they receive: they must be willing/capable of ignoring terms they don't currently understand. This may well be standard practice within the JSON-LD community, but I think it would be good to call out a thorough description of (a) what things constitute "change" in our specs, and (b) how we consider those changes (are they breaking, non-breaking), and thereby (c) what responsibilities senders and receivers of data have regarding the versions of the data they send and receive.

It's possbile the best place for this is in an implementation or best practices enablement doc, and not necessarily the normative specifications themselves.

**Comment by ottonomy** [comment]
👍 I agree that a description of what constitutes breaking changes to contexts/spec should be added to the specs. Maybe a paragraph presented at the top of any errata/history/changelog content. I think the goal of things that we call "non-breaking changes" is that they don't impose much costs on implementers, either issuers or consumers. 

Context:
The example change for this is "add the term `identifier` to the CLR context where it may appear in nodes of type `ClrSubject`." Let's look at how an issuer and a verifier of a ClrCredential might need to understand or react to this change.

As an issuer of ClrCredentials, if you previously included `identifier` at this level, it had been dropped upon any JSON-LD processing operation. No change is needed to your system, but now the term will not be dropped by consumers (or by your cryptographic signing library) anymore. Bug fixed.

As a consumer of ClrCredentials, now when I verify a ClrCredential where the issuer had included an identifier for the user at this level, it will now show up, whereas previously it would not have appeared if any JSON-LD operation had been done on the data. No other change to software is necessary.

**Comment by amiller-ims** [comment]
>
> As an issuer of ClrCredentials, if you previously included identifier at
> this level, it had been dropped upon any JSON-LD processing operation.


One of the signing libraries I use will refuse to sign the credential if
there is an unknown term. Definitely a bug. Adding the term to the context
will fix that bug too.

**Comment by xaviaracil** [comment]
As agreed by the working group: add paragraph about policy about changes in two places:

- Implementation guide
- Errata document

**Comment by xaviaracil** [comment]
@ottonomy @ViktorHaag @amiller-ims 
Written a section in the errata document at https://github.com/1EdTech/openbadges-specification/pull/519/files

If approved, I'll copy it into the Implementation Guide

**Comment by xaviaracil** [comment]
@ViktorHaag comments and suggestions included in a new commit.
