### ISSUE TITLE
`tag` and `achievementType` seem redundant

### ISSUE THREAD

**Issue by amiller-ims** [1EdTech/openbadges-specification#516]
`tag` is defined as, "Tags that describe the type of achievement."

`achievementType` is defined as, "The type of achievement."

Since `tag` is freeform text, and `achievementType` is a machine-readable extensible vocabulary, I suggest removing the `tag` property.

If there are use cases for keeping both, then I suggest clarifying the difference in the definitions.

**Comment by ottonomy** [comment]
`tag` is a keyword (0 to many values), not necessarily attempting to indicate type (which is 0 to 1 possible values). I don't think a `[0..1]` field is an adequate replacement for an `[0..*]` field.

**Comment by xaviaracil** [comment]
As agreed by the working group: Improve the description of the `tag` field to break this redundancy.
