### ISSUE TITLE
`tag` is described as a "comma delimited string" and modeled as a set of strings

### ISSUE THREAD

**Issue by andyfmiller** [1EdTech/openbadges-specification#520]
https://github.com/1EdTech/openbadges-specification/blob/643bbc9549ecc4cc6c368f8616714878a5eb942f/ob_v3p0/common_credentials.lines#L25

Is this a mistake? It sounds like an array of arrays of strings. I suspect the model should be:
```
Property tag String 0..* array-compacted "One or more short, human-friendly, searchable, keywords that describe the type of achievement."
```

Note in OB2.0, the property name is `tags` and it is modeled as a single string value or a set of strings: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#BadgeClass

**Comment by ottonomy** [comment]
Do we leave issues open after they are fixed for some reason?

Indeed, the design intent here has always been a set/array of strings when multiple tags are used. OB 2.0 was less strict about how single values were serialized for properties that accepted multiple values. `"tag1"` was treated as equivalent to `["tag1"]`.

**Comment by xaviaracil** [comment]
My fault @ottonomy. Somehow I didn't close the issue.

Sorry  about that
