### ISSUE TITLE
Misuse of @language in examples and i18n documentation

### ISSUE THREAD

**Issue by ottonomy** [1EdTech/openbadges-specification#550]
I was tipped off this week that Open Badges since 2.0 has made a slight misuse of the `@language` JSON-LD keyword. For example, in the [Achievement](https://www.imsglobal.org/spec/ob/v3p0/#achievement) class, `@language` appears as a property.

In the JSON-LD spec, [string internationalization](https://www.w3.org/TR/json-ld/#string-internationalization) is done with a `@language` key in the context, not in the body of the document.
```
{
  "@context": {
    "name": "http://example.org/name",
    "occupation": "http://example.org/occupation",
    ...
    "@language": "ja"
  },
  "name": "花澄",
  "occupation": "科学者"
}
```

In the body of the document, using the reserved keyword varies between having no effect and being entirely dropped in certain representations.

Demonstrations of issue:
* In this [example of using `@language` in a document](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22name%22%3A%22https%3A%2F%2Fschema.org%2Fname%22%7D%2C%22%40language%22%3A%22en%22%2C%22name%22%3A%22John%20Doe%22%7D&context=%7B%22%40context%22%3A%7B%22name%22%3A%22https%3A%2F%2Fschema.org%2Fname%22%7D%7D), observe that (a) `@language` does appear as expected in expanded and compacted forms, but (b) it is entirely dropped from N-Quads. This means that after certain JSON-LD processing operations, including some involved in cryptographic signing of credentials, this data is being dropped. 
* In this example using the [OB context](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fpurl.imsglobal.org%2Fspec%2Fob%2Fv3p0%2Fcontext-3.0.2.json%22%5D%2C%22type%22%3A%22Achievement%22%2C%22name%22%3A%22Example%20Badge%22%2C%22%40language%22%3A%22en%22%2C%22related%22%3A%7B%22type%22%3A%22Related%22%2C%22id%22%3A%22https%3A%2F%2Fexample.com%22%2C%22%40language%22%3A%22es%22%7D%7D), observe the same features, notably that both `@language` references are completely dropped from N-Quads form. The desired results do still appear in compacted form, which is why we missed this bug for so long.

Possible actions:
1. Do nothing. Some occasional bugs would remain and language values would be dropped during certain JSON-LD operations. 
2. Add a new property `inLanguage` to the context, such as with the https://schema.org/inLanguage IRI and update relevant classes, schema, and examples in implementation guide to use that property. This completely solves the problem with very little "splash damage". But it doesn't take advantage of any JSON-LD special features for string labeling.
3. Adapt all string properties to use expanded form `{["@value": ..., "@language": ..., "@direction"]}`, making a large change to schemas and still not solving for the use case of "what language is this document in?" or "what language is this related document in?". This would only be a partial solution.
4. Use implementer contexts like `"@context": ["https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.2.json", {"@language": "en"}]` that include a document language. Downside is this applies to binary string properties as well that aren't really in a language. This also is a partial solution, because it doesn't work for the other use case of describing what language a `related` document is in.

Meanwhile, discussion of i18n is ongoing related to the forthcoming VC 2.0 documentation, including experts from i18n community at W3C as well as negotiating the balance for implementers who do not wish to use any JSON-LD processing tools, like we do in OB and CLR by also restricting credentials to a specific JSON-schema. In JSON-LD, all the following values represent a single string value, but require consumers to be ready to handle any of them for a term like `Achievement.name` which should just be a singular string.

`"name": "Name"`
`"name": ["Name"]`
`"name": {"@value": "Name", "@language": "en"}`
`"name": [{"@value": "Name", "@language": "en"}]`
```
"@context": {"name": {"@id": "https://schema.org/name", "@container": "@language"} },
"name": {"en": "Name"},
```

**Comment by xaviaracil** [comment]
Another option is following 1EdTech's Localization Framework, still in preview. It follows a decoration pattern, where the decorations are in a new attribute, `localizationData`, which leverages jsonpath to define the attributes to decorate.

For example:
```json
"localizationData": {
    "local": {
      "items": [{
        "select": "$.credentialSubject.achievement",
        "apply": [{
          "language": "sv",
          "value": "geografi, matematik"
        }, {
          "language": "fr",
          "value": "géographie, mathématiques"
        }]
      }]
    }
  }
```

I can give more details of the framework in the meeting
