### ISSUE TITLE
Multiplicity on '@context' properties with more than 1 required member element is incorrect

### ISSUE THREAD

**Issue by Klowes** [1EdTech/openbadges-specification#572]
Example:

EndorsementCredential's @context property has a multiplicity of "[1..*]" despite requiring a first element of value 'https://www.w3.org/ns/credentials/v2', and second element of value 'https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.3.json'

**Comment by Klowes** [comment]
submitted https://github.com/1EdTech/openbadges-specification/pull/573

**Comment by xaviaracil** [comment]
Fixed via internal tooling
