### ISSUE TITLE
Broken recipientProfile extension URL

### ISSUE THREAD

**Issue by herman-toothrot** [1EdTech/openbadges-specification#579]
Hi there, not sure if this is the right place:

We noticed that the URL for the `recipientProfile` extension (`https://openbadgespec.org/extensions/recipientProfile/context.json`) seems to be broken from some time after 31.05.2024 13:00 CEST.
It just redirects to `https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html` breaking badge assertions using a self hosted badgr-server.
Also, already asserted badges using the `recipientProfile` extension are failing validation using [badgecheck.io ](https://badgecheck.io/) because the context.json/schema.json of the extension can't be loaded anymore.
Was the extension metadata removed intentionally? What's the intended way to fix it?

**Comment by andreyferriyan** [comment]
I have the same situation. Do you have any solution for this? Should we make our community extensions?

**Comment by xaviaracil** [comment]
@herman-toothrot @andreyferriyan It should work now. An issue in openbadgespec.org prevented the right resolution of extension-related files (context and schema, basically). This issue has been fixed.
