### ISSUE TITLE
VCDM 2.0 Schema Requirement for AchievementCredential 

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#583]
Hello!

The spec links to this schema: [https://purl.imsglobal.org/spec/ob/v3p0/schema/json/ob_v3p0_achievementcredential_schema.json](https://purl.imsglobal.org/spec/ob/v3p0/schema/json/ob_v3p0_achievementcredential_schema.json ) at [https://www.imsglobal.org/spec/ob/v3p0#json-schema-0](https://www.imsglobal.org/spec/ob/v3p0#json-schema-0)

and the schema requires the VCDM @context file: 

```
"description" : "AchievementCredentials are representations of an awarded achievement, used to share information about a achievement belonging to one earner. Maps to a Verifiable Credential as defined in the [[VC-DATA-MODEL-2.0]]. As described in [[[#data-integrity]]], at least one proof mechanism, and the details necessary to evaluate that proof, MUST be expressed for a credential to be a verifiable credential. In the case of an embedded proof, the credential MUST append the proof in the `proof` property.",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "minItems" : 2,
      "items" : [ {
        "enum" : [ "https://www.w3.org/ns/credentials/v2" ]
      }, {
        "type" : "string",
        "pattern" : "^https:\\/\\/purl\\.imsglobal\\.org\\/spec\\/ob\\/v3p0\\/context(-3\\.\\d\\.\\d)*\\.json$"
      } ],
      "additionalItems" : {
        "$ref" : "#/$defs/Context"
      }
    },
```

but VCDM 2.0 is not final so it should be an option to use 1.0 or 2.0.

In [AnyAchievmentCredential](https://www.imsglobal.org/spec/ob/v3p0#anyachievementcredential-0), it is noted that: "AnyAchievementCredential represents an AchievementCredential that might be built using [[VC-DATA-MODEL](https://www.imsglobal.org/spec/ob/v3p0#bib-vc-data-model)] or [[VC-DATA-MODEL-2.0](https://www.imsglobal.org/spec/ob/v3p0#bib-vc-data-model-2.0)]"

Is it possible that the wrong schema is being linked to or that this info should be included in the schema for AcheivementCredential as well?

Thanks

**Comment by kayaelle** [comment]
This is also related to: [https://github.com/1EdTech/digital-credentials-public-validator](https://github.com/1EdTech/digital-credentials-public-validator)

**Comment by xaviaracil** [comment]
The working group decided to promote the issuance of credentials with the new VCDM 2.0 version, while the verification can be done against either VCDM 1.1 or VCDM 2.0.

To support that promotion, the schema for AchievementCredential and EndorsementCredential requires the VCDM 2.0 context.

For verification purposes, new AnyAchievementCredential and AnyEndorsementCredential entities were defined with support for both versions of the VCDM context in their schemas.

**Comment by kayaelle** [comment]
I recommend we align AchievementCredential and EndorsementCredential with AnyAchievementCredential and AnyEndorsementCredential while we are in this transition stage and until VCDM 2.0 is final. 

We want to support VCDM 2.0 but not precede it.

**Comment by xaviaracil** [comment]
Document updated as per workgroup meeting agreement
